# @package _global_

distribution:
  _target_: mutinfo.distributions.tools.mapped_multi_rv_frozen
  base_rv:
    _target_: mutinfo.distributions.base.UniformlyQuantized
    mutual_information: ${processed.mutual_information}
    dimensionality: ${raw.dimensionality}
    base_rv:
      _target_: scipy.stats.uniform
    normalize: true
    randomize_interactions: false
  mapping:
    _target_: mutinfo.distributions.tools.cartesian_product_of_functions
    _args_:
      - _target_: mutinfo.distributions.images.field.draw_field
        _partial_: true
        field_function:
          _target_: mutinfo.distributions.images.field.symmetric_gaussian_field
          _partial_: true
        grid_shape:
          - ${raw.image_dimensionality}
          - ${raw.image_dimensionality}
      - _target_: mutinfo.distributions.images.field.draw_field
        _partial_: true
        field_function:
          _target_: mutinfo.distributions.images.field.symmetric_gaussian_field
          _partial_: true
        grid_shape:
          - ${raw.image_dimensionality}
          - ${raw.image_dimensionality}

raw:
  dimensionality: 2

distribution_key: 2d_gaussian_${raw.image_dimensionality}x${raw.image_dimensionality}/MI=${distribution.base_rv.mutual_information}

hydra:
  sweeper:
    params:
      ++raw.mutual_information: ${default_grid.mutual_information}
      ++raw.image_dimensionality: ${default_grid.image_dimensionality}
