# @package _global_

distribution:
  _target_: mutinfo.distributions.tools.mapped_multi_rv_frozen
  base_rv:
    _target_: mutinfo.distributions.base.UniformlyQuantized
    dimensionality: 4
    base_rv:
      _target_: scipy.stats.uniform
    normalize: true
    randomize_interactions: false
  mapping:
    _target_: mutinfo.distributions.tools.cartesian_product_of_functions
    _args_:
      - _target_: builtins.eval
        _args_: ["lambda x : eval('exec(\"from mutinfo.distributions.images.geometric import uniform_to_rectangle, draw_rectangle\") or draw_rectangle(uniform_to_rectangle(x, min_size=(0.2, 0.2)), (${dimensionality}, ${dimensionality}))')"]
      - _target_: builtins.eval
        _args_: ["lambda x : eval('exec(\"from mutinfo.distributions.images.geometric import uniform_to_rectangle, draw_rectangle\") or draw_rectangle(uniform_to_rectangle(x, min_size=(0.2, 0.2)), (${dimensionality}, ${dimensionality}))')"]

distribution_key: 2d_rectangle_${dimensionality}x${dimensionality}/MI=${distribution.base_rv.mutual_information}

hydra:
  sweeper:
    params:
      #~distribution: mutual_information # Delete parameter.
      ++distribution.base_rv.mutual_information: ${default_grid.mutual_information}
      ++dimensionality: ${default_grid.image_dimensionality}
