# @package _global_

name:
  estimator: cFMMI

estimator:
  _target_: mutinfo.estimators.parametric.fmmi.cFMMI
  parameters:
    marginalizer:
      _target_: fmmi.estimator.mi.generate_permutation
      _partial_: true
  backbone_factory:
    _target_: mutinfo.estimators.parametric.fmmi.conditional_VelocityModelMLP_wrapper
    _partial_: true
    hidden_dim: 512
    dropout: 0.01
  optimizer_factory:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1.0e-3
    weight_decay: 0.0
  n_train_steps: 100000
  train_batch_size: 512
  estimate_batch_size: 512
  estimate_fraction: 10000 # `null` for no splitting.
  device: "cuda"

parameters_counter:
  _target_: builtins.eval
  _args_: ["lambda estimator, x, y: sum(parameters.numel() for parameters in estimator.backbone_factory(x.shape, y.shape).parameters())"]

key:
  estimator: ${name.estimator}/hidden=${estimator.backbone_factory.hidden_dim}

hydra:
  sweeper:
    params:
      ++estimator.parameters.reverse: False, True
      #++estimator.optimizer_factory.weight_decay: 0.0, 1.0e-4
      ++estimator.backbone_factory.dropout: 0.01, 0.05
      #++estimator.backbone_factory.hidden_dim: 128, 256, 512
      #++estimator.parameters.marginalizer._target_: fmmi.estimator.mi.generate_permutation, fmmi.estimator.mi.generate_derangement