# @package _global_

name:
  estimator: KSG

estimator:
  _target_: mutinfo.estimators.knn.KSG

key:
  estimator: ${name.estimator}/k=${estimator.k_neighbors}

hydra:
  sweeper:
    params:
      ++estimator.k_neighbors: 1, 2, 3, 5, 10, 20
