# @package _global_

estimator:
  _target_: mutinfo.estimators.neural.mine.MINE
  n_train_steps: 10000
  estimate_fraction: null # Do not split.
  device: "cuda"
  #preprocessor:
  #  _target_: mutinfo.estimators.base.JointTransform
  #  transforms:
  #  - _target_: sklearn.preprocessing.RobustScaler
  #  - _target_: sklearn.preprocessing.RobustScaler
  #backbone_factory:
  #  _target_: mutinfo.estimators.neural.mine.GenericConv2dClassifier
  #  _partial_: true