# @package _global_

estimator:
  _target_: mutinfo.estimators.neural.mine.MINE
  n_train_steps: 10000
  device: "cuda"
  loss_factory:
    _target_: builtins.eval
    #_args_: ["exec('import torchkld') or (lambda : torchkld.loss.NWJLoss())"]        # Not working for some reason.
    _args_: ["lambda : eval('exec(\"import torchkld\") or torchkld.loss.NWJLoss()')"] # This is actually insane...
  #preprocessor:
  #  _target_: mutinfo.estimators.base.JointTransform
  #  transforms:
  #  - _target_: sklearn.preprocessing.RobustScaler
  #  - _target_: sklearn.preprocessing.RobustScaler
  backbone_factory:
    _target_: mutinfo.estimators.neural.mine.GenericConv2dClassifier
    _partial_: true