# @package _global_

name:
  estimator: WKL

estimator:
  _target_: mutinfo.estimators.knn.WKL

key:
  estimator: ${name.estimator}/k=${estimator.k_neighbors}

hydra:
  sweeper:
    params:
      ++estimator.k_neighbors: 1, 5, 9, 13, 17
