# @package _global_

modulation_distribution:
  _target_: mutinfo.distributions.base.CorrelatedUniform
  dimensionality: 1

modulator:
  _target_: builtins.eval
  _args_: ["lambda x_tuple, y_tuple : tuple(x * y.reshape((-1,) + (1,) * (len(x.shape) - 1)) for x, y in zip(x_tuple, y_tuple))"]

hydra:
  sweeper:
    params:
      ++modulation_distribution.mutual_information: ${default_grid.mutual_information}