# @package _global_

name:
  distribution: LogGammaExponential

distribution:
  _target_: mutinfo.distributions.base.LogGammaExponential
  mutual_information: ${processed.mutual_information}
  dimensionality: ${raw.dimensionality}

key:
  distribution: ${name.distribution}/dim=${distribution.dimensionality}/MI=${round:${raw.mutual_information}}

hydra:
  sweeper:
    params:
      ++raw.mutual_information: ${default_grid.mutual_information}
      ++raw.dimensionality: ${default_grid.dimensionality}