# @package _global_

distribution:
  _target_: mutinfo.distributions.base.LogGammaExponential

distribution_key: dim=${distribution.dimensionality}

hydra:
  sweeper:
    params:
      ++distribution.dimensionality: ${default_grid.dimensionality}
