# @package _global_

distribution:
  _target_: mutinfo.distributions.base.MixtureUniform
  mutual_information: ${processed.mutual_information}
  dimensionality: ${raw.dimensionality}
  normalize: true

distribution_key: dim=${distribution.dimensionality}/MI=${raw.mutual_information}

hydra:
  sweeper:
    params:
      ++raw.mutual_information: ${default_grid.mutual_information}
      ++raw.dimensionality: ${default_grid.dimensionality}
