# @package _global_

distribution:
  _target_: mutinfo.distributions.base.MixtureUniform
  normalize: true

distribution_key: dim=${distribution.dimensionality}/MI=${distribution.mutual_information}

hydra:
  sweeper:
    params:
      ++distribution.mutual_information: ${default_grid.mutual_information}
      ++distribution.dimensionality: ${default_grid.dimensionality}
