# @package _global_

name:
  distribution: SmoothedQuantized

distribution:
  _target_: mutinfo.distributions.base.SmoothedQuantized
  dimensionality: ${raw.dimensionality}
  normalize: true

key:
  distribution: ${name.distribution}/dim=${distribution.dimensionality}/m=${distribution.alphabet_size}/n=${distribution.smoothing_epsilon}

hydra:
  sweeper:
    params:
      ++distribution.alphabet_size: 2, 4, 8, 16, 32, 64, 128, 256, 512
      ++distribution.smoothing_epsilon: 2, 3 #, 4, 5
      ++raw.mutual_information: 0 # TODO: proper key removal?
      ++raw.dimensionality: ${default_grid.dimensionality}
