# @package _global_

labels_distribution:
  _target_: mutinfo.distributions.base.NoiselessChannel
  permute: True

hydra:
  sweeper:
    params:
      ++labels_distribution.mutual_information: ${default_grid.mutual_information}