n_runs: 10
seed: 42
to_be_seeded:
  - basic
  - numpy
  - torch

default_grid:
  mutual_information: 0.0, 1.0, 5.0, 10.0
  nonzero_mutual_information: 1.0, 5.0, 10.0
  dimensionality: range(1, 3)

hydra:
  mode: MULTIRUN
  sweep:
    dir: outputs/${now:%Y-%m-%d}
    subdir: ${estimator._target_}/${distribution._target_}/${distribution_key}/N=${n_samples}/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}
  sweeper:
    max_batch_size: 100 # Makes startup faster, see https://github.com/facebookresearch/hydra/issues/1324.
    params:
      ++distribution.mutual_information: ${default_grid.mutual_information}
      ++n_samples: 1000, 10000
