# @package _global_

name:
  distribution: labels/MNIST

default_grid:
  mutual_information: 0.0, 0.5, 1.0, 1.5, 2.0, 2.3 #range(0.0, 2.4, 0.2)

_subsamplers:
  _target_: mutinfo.distributions.mixing.label.torchvision_labeled_dataset_to_subsamplers
  dataset:
    _target_: torchvision.datasets.MNIST # List inside list.
    root: "./.cache"
    download: True

distribution:
  _target_: mutinfo.distributions.mixing.label.mixed_by_label
  marginal_distributions:
    - ${_subsamplers}
    - ${_subsamplers}
  labels_distribution: ${labels_distribution}

n_samples: 50000

key:
  distribution: ${name.distribution}/${key.labels_distribution}