name: highdim/sample_complexity/estimator_dimensionality-hidden_dim-MAE

sources:
  cFMMI:
    path: "./outputs/highdim/FMMI/sample_complexity/cFMMI"
    aggregate: ["estimator.estimator.estimator_factory.marginalizer._target_"]
    pin: {}
    priority: 0
  jFMMI:
    path: "./outputs/highdim/FMMI/sample_complexity/jFMMI"
    aggregate: ["estimator.estimator.estimator_factory.marginalizer._target_"]
    pin: {}
    priority: 0

targets:
  - name: "RMAE"
    function:
      _target_: __main__.RMAE
      _partial_: true
      first: "target"
      second: "estimate.median"

outputs: ["RMAE"]

aggregation:
  by: "RMAE"
  output: "RMAE"

column_to_chart:
  name: "estimator.estimator.backbone_factory.hidden_dim"

rows_to_chart: ["Source", "Distribution", "raw.dimensionality"]
pin:
  raw.mutual_information: 2.0
  n_samples: 10000