name: kNN/KSG_MAE_vs_kNN

sources:
  KSG:
    path: "./outputs/lowdim/2025-10-20/KSG"
    aggregate: []
    pin: {}
    priority: 0

targets:
  - name: "MAE"
    function:
      _target_: __main__.MAE
      _partial_: true
      first: "distribution.mutual_information"
      second: "mutual_information.mean"

outputs: ["MAE"]

aggregation:
  by: "MAE"
  output: "MAE"

column_to_chart:
  name: "estimator.k_neighbors"
  apply:
    _target_: builtins.int
    _partial_: true

rows_to_chart: ["Distribution"]
pin: {}